version: '3.8'

services:
  app:
    build: .
    container_name: coffee-shop
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/coffee-test?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    expose:
      - "8080"
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: coffee-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coffee-test
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge